# Generated by Django 3.1.7 on 2021-02-20 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
