# Generated by Django 3.1.7 on 2021-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_categories',
            field=models.ManyToManyField(related_name='provider', to='news.Categories', verbose_name='List for sub categories'),
        ),
    ]
