# Generated by Django 3.1.7 on 2021-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0004_auto_20210220_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
