# Generated by Django 3.1.7 on 2021-02-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
